### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by 18729595064** [kmsiapps/Semantic-Communications-with-a-Vision-Transformer#1]
May I ask if there is a PyTorch version of the code available

**Comment by kmsiapps** [comment]
I'm sorry there's not, but you may start with Pytorch version of deep image compression codes (such as https://github.com/InterDigitalInc/CompressAI)

**Comment by 18729595064** [comment]
Hello, thank you for your reply.
I will try running your code on Windows 10. Attempted Python 3.8, 3.9, 3.10, but encountered version errors:
For example, on Python 3.10, I will report: Error: Ignored the following versions that require a different Python version: 1.6.2 Requirements Python&gt;=3.7,<3.10; 1.6.3 Requirements Python&gt;=3.7,<3.10; 1.7.0 Requirements Python&gt;=3.7,<3.10; 1.7.1 Requirements Python&gt;=3.7,<3.10
Error: Could not find a version that satisfies the requirement tensorflow compression (from versions: none)
Error: No matching distribution found for tensorflow compression
On Python 3.9, it will also report: Error: Ignored the following versions that require a different Python version: 8.19.0 Requirements Python&gt;=3.10; 8.20.0 Requirements Python&gt;=3.10
Error: Could not find a version that satisfies the requirement tensorflow compression=2.11.0 (from versions: none)
Error: No matching distribution found for tensorflow compression=2.11.0
May I ask if your project code cannot run on Windows or not?
Looking forward to your reply, thank you!
Wishing you smooth work and all the best.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kmsiapps/Semantic-Communications-with-a-Vision-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月9日(星期二) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kmsiapps/Semantic-Communications-with-a-Vision-Transformer] PyTorch version (Issue #1)





 
I'm sorry there's not, but you may start with Pytorch version of deep image compression codes (such as https://github.com/InterDigitalInc/CompressAI)

**Comment by kmsiapps** [comment]
I'm not sure, but I'm using linux environments for this project. Maybe you can try windows subsystem for linux (WSL) and use official tensorflow docker image?
